project:
  name: "robot"
  environment: "development"

server:
  host: "localhost"
  port: 8000

mongdb:
  user: "admin"
  pass: "1q2w3e4r"
  host: "localhost"
  port: 27017
  database: "robot"
  type: "mongdb"