x-golang-port: &golang-port
  - "8080:8000"

x-robot-net: &robot-net
  - robotnet

version: '3.8'
services:
  backend-robot:
    build:
      context: ./service/
      dockerfile: Dockerfile
    container_name: be-golang
    restart: always
    ports: *golang-port
    command: sh -c "./main"
    networks: *robot-net

  frontend-robot:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: fe-react
    restart: always
    ports: *golang-port
    command: sh -c "npm start"
    networks: *robot-net

networks: 
  robotnet: