name: STAGING
on:
  push:
    branches:
    - golang
  pull_request:
    branches:
    - golang
env:
  # Variable name
  PROJECT_NAME: robot

  # dockerhub container
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  backend:
    name: Building image robot backend
    runs-on: ubuntu-latest
    steps:

    # [Step-1] check config git
    - uses: actions/checkout@v2

    # [Step-2] login dockerhub container
    - name: Login to DockerHub Registry
      run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
    
    # [Step-3] buid and tag image from Dockerfile
    - name: Build and tag the image
      run: |
        docker build -t golang -t $DOCKERHUB_USERNAME/robot-golang:latest ./service/
    
    # [Step-4] Push image to docker hub
    - name: Push image to DockerHub
      run: |
        docker push $DOCKERHUB_USERNAME/robot-golang:latest